#!/usr/bin/env python3
"""Emit the simplified landscape as TikZ, sized natively for an IEEE figure*.

The SVG version is 1400pt wide; scaled into a 516pt two-column figure its type
would fall to about 4pt. This lays the same content out at 516pt directly, one
line per entry (name + year), so the type stays near 7pt.

TikZ rather than an image: no conversion step, vector output, and the figure
picks up the document's own font. Requires only \\usepackage{tikz}.

Data is read from make_landscape.py by AST. Writes review/fig-landscape.tex.
Regenerate: python3 assets/make_landscape_tikz.py
"""
import ast, re, os

src = ast.parse(open("assets/make_landscape.py").read())
D = {}
for n in src.body:
    if isinstance(n, ast.Assign) and isinstance(n.targets[0], ast.Name) and n.targets[0].id.isupper():
        try: D[n.targets[0].id] = ast.literal_eval(n.value)
        except Exception: pass

def esc(s):
    s = (s.replace("\\", "").replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")
          .replace("#", r"\#").replace("“", "``").replace("”", "''").replace("’", "'"))
    return s

def year(venue):
    m = re.findall(r'(1[89]\d{2}|20\d{2})', venue)
    return m[-1] if m else (venue.split()[0] if venue else "")

W, COLW, GAP, ROW = 516.0, 123.0, 8.0, 11.6
X = [0.0, COLW + GAP, 2 * (COLW + GAP), 3 * (COLW + GAP)]
L = []
def out(s): L.append(s)

def entry(x, y, name, venue, dashed=False):
    style = "sysbox" + (",dashbox" if dashed else "")
    out(f"  \\node[{style}] at ({x:.1f}pt,{y:.1f}pt) "
        f"{{\\sysname{{{esc(name)}}}\\hfill\\sysyear{{{esc(year(venue))}}}}};")

def group(x, y, title, items, dashed=False):
    out(f"  \\node[grouphead] at ({x:.1f}pt,{y:.1f}pt) "
        f"{{{esc(title)}\\hfill\\textcolor{{lsgrey}}{{{len(items)}}}}};")
    out(f"  \\draw[lsrule] ({x:.1f}pt,{y-6.2:.1f}pt) -- ({x+COLW:.1f}pt,{y-6.2:.1f}pt);")
    cy = y - 15.0
    for e in items:
        entry(x, cy, e[0], e[1], dashed); cy -= ROW
    return cy - 5.0

out(r"% Generated by assets/make_landscape_tikz.py -- do not edit by hand.")
out(r"\begin{figure*}[t]\centering")
out(r"\begingroup")
out(r"\definecolor{lsink}{HTML}{0B0B0B}\definecolor{lsmid}{HTML}{52514E}")
out(r"\definecolor{lsgrey}{HTML}{898781}\definecolor{lsrulec}{HTML}{D9D8D1}")
out(r"\definecolor{lsfill}{HTML}{F4F3EF}")
out(r"\tikzset{")
out(r"  sysbox/.style={anchor=north west, inner sep=1.6pt, text width=" + f"{COLW-3.2:.1f}" + r"pt,"
    r" font=\fontsize{6.9}{7.6}\selectfont, text=lsink},")
out(r"  dashbox/.style={draw=lsgrey, dashed, dash pattern=on 1.6pt off 1.4pt, line width=0.3pt},")
out(r"  grouphead/.style={anchor=north west, inner sep=0pt, text width=" + f"{COLW:.1f}" + r"pt,"
    r" font=\fontsize{6.2}{6.8}\bfseries\selectfont, text=lsmid},")
out(r"  lsrule/.style={draw=lsrulec, line width=0.4pt},")
out(r"  banner/.style={anchor=north west, inner sep=0pt, font=\fontsize{6.2}{7}\selectfont, text=lsgrey}}")
out(r"\newcommand{\sysname}[1]{\textbf{#1}}")
out(r"\newcommand{\sysyear}[1]{\textcolor{lsgrey}{\fontsize{5.9}{6.4}\selectfont #1}}")
out(r"\begin{tikzpicture}[x=1pt,y=1pt]")

y = 0.0
out(r"  \node[grouphead] at (0pt,0pt) {CLASSICAL DISCOVERY PROGRAMMES (PRE-LLM)"
    r"\hfill\textcolor{lsgrey}{4 systems, 2 publications}};")
out(f"  \\draw[lsrule] (0pt,-6.2pt) -- ({W:.1f}pt,-6.2pt);")
y = -15.0
for i, c in enumerate(D["CLASSICAL"]): entry(X[i], y, c[0], c[1])
entry(X[3], y, D["ADAM"][0], D["ADAM"][1])
y -= ROW
entry(X[0], y, D["BOOK"][0], D["BOOK"][1], dashed=True)
entry(X[1], y, D["AUTOM"][0], D["AUTOM"][1], dashed=True)
out(f"  \\node[banner] at ({X[2]:.1f}pt,{y:.1f}pt) {{\\itshape publications, held separate}};")
y -= ROW + 6

out(f"  \\draw[lsrule, dash pattern=on 2pt off 2.5pt] (0pt,{y:.1f}pt) -- ({W:.1f}pt,{y:.1f}pt);")
out(f"  \\node[banner, anchor=north, fill=white, inner xsep=4pt] at ({W/2:.1f}pt,{y+3.4:.1f}pt) "
    r"{contemporary systems: LLM agents, program search \& autonomous labs};")
y -= 12

COLUMNS = [[("GENERAL / CROSS-DOMAIN", D["GENERAL"], False), ("LITERATURE \\& EVIDENCE", D["LIT"], False)],
           [("CHEMISTRY / MATERIALS", D["CHEM"], False), ("ML ENGINEERING", D["MLENG"], False)],
           [("BIOLOGY / LIFE SCIENCES", D["BIOLOGY"], False), ("SELF-DRIVING LABS", D["LABS"], False)],
           [("PROGRAM \\& EQUATION DISCOVERY", D["PROGRAM"], False), ("NON-SYSTEM ENTRIES", D["NONSYS"], True)]]
bottoms = []
for ci, stack in enumerate(COLUMNS):
    cy = y
    for (t, items, dashed) in stack:
        cy = group(X[ci], cy, t, items, dashed) - 4
    bottoms.append(cy)
yb = min(bottoms) - 4
nsys = sum(len(D[k]) for k in ("GENERAL", "BIOLOGY", "LABS", "PROGRAM", "MLENG", "CHEM", "LIT"))
out(f"  \\draw[lsrule] (0pt,{yb:.1f}pt) -- ({W:.1f}pt,{yb:.1f}pt);")
out(f"  \\node[banner] at (0pt,{yb-3:.1f}pt) {{{nsys} contemporary systems, 4 classical systems, "
    f"{len(D['NONSYS'])} non-system entries, 2 foundational publications. "
    r"Panels are categories, not lineages. Venues verified 29 July 2026.};")
out(r"\end{tikzpicture}")
out(r"\endgroup")
out(r"\caption{Landscape of AI-enabled scientific-discovery systems, grouped by application "
    r"area. Position and adjacency carry no claim of descent. Benchmarks and agenda papers are "
    r"held separate from systems and are excluded from every ratio reported in this review.}")
out(r"\label{fig:landscape}")
out(r"\end{figure*}")

os.makedirs("review", exist_ok=True)
open("review/fig-landscape.tex", "w").write("\n".join(L) + "\n")
print(f"wrote review/fig-landscape.tex  ({nsys} systems, width {W:.0f}pt)")
