#!/usr/bin/env python3
"""Emit the discovery-loop figure as TikZ for the review.

Same content as assets/ai-scientist-overview.svg: four stages in a cycle, the
return edge that closes it, and the six things that can play the role of
"experiment / evaluation", ordered by evidential strength.

TikZ rather than an image: no conversion step, and it picks up the document
font. Needs only \\usepackage{tikz}; \\circlearrowleft comes from amssymb,
already loaded by the IEEE template.

Writes review/fig-loop.tex. Regenerate: python3 assets/make_overview_tikz.py
"""
import os

STAGES = ["Represented hypothesis", "Experiment / evaluation", "Evidence",
          "Retention $\\cdot$ revision $\\cdot$ rejection"]
MODES = [("V1", "self-critique"), ("V2", "agent debate"), ("V3", "execution"),
         ("V4", "statistics"), ("V5", "empirical experiment"), ("V6", "formal verification")]

BW, BH, STEP = 168.0, 24.0, 40.0
CX = 96.0                      # centre of the stage column
RX = CX - BW / 2 - 26          # x of the return edge
PX, PW = 268.0, 208.0          # modes panel
ys = [-(20 + i * STEP) for i in range(4)]

L = []
def o(s): L.append(s)

o(r"% Generated by assets/make_overview_tikz.py -- do not edit by hand.")
o(r"\begin{figure*}[t]\centering")
o(r"\begingroup")
o(r"\definecolor{lpink}{HTML}{0B0B0B}\definecolor{lpmid}{HTML}{52514E}")
o(r"\definecolor{lpgrey}{HTML}{8A8880}\definecolor{lprule}{HTML}{D5D4CD}")
o(r"\definecolor{lpacc}{HTML}{2A78D6}")
o(r"\tikzset{")
o(r"  stage/.style={draw=lpink, line width=0.7pt, rounded corners=2pt, minimum width=" + f"{BW:.0f}" +
  r"pt, minimum height=" + f"{BH:.0f}" + r"pt, align=center, font=\fontsize{7.8}{9}\bfseries\selectfont, text=lpink},")
o(r"  flow/.style={draw=lpmid, line width=0.8pt, ->},")
o(r"  back/.style={draw=lpacc, line width=0.9pt, ->},")
o(r"  hint/.style={draw=lprule, line width=0.7pt, dashed, dash pattern=on 2pt off 1.6pt, ->},")
o(r"  panel/.style={draw=lprule, line width=0.7pt, rounded corners=3pt},")
o(r"  lbl/.style={font=\fontsize{6.2}{7}\selectfont, text=lpacc},")
o(r"  mode/.style={anchor=west, font=\fontsize{7.4}{8}\selectfont, text=lpink},")
o(r"  rung/.style={anchor=west, font=\fontsize{6.4}{7}\bfseries\selectfont, text=lpgrey},")
o(r"  head/.style={anchor=west, font=\fontsize{6.6}{7}\bfseries\selectfont, text=lpmid},")
o(r"  axis/.style={draw=lpgrey, line width=0.7pt, ->}}")
o(r"\begin{tikzpicture}[x=1pt,y=1pt]")

for i, (s, y) in enumerate(zip(STAGES, ys)):
    o(f"  \\node[stage] (s{i}) at ({CX:.1f}pt,{y:.1f}pt) {{{s}}};")
for i in range(3):
    o(f"  \\draw[flow] (s{i}.south) -- (s{i+1}.north);")

# the return edge
o(f"  \\draw[back] (s3.west) -- ({RX:.1f}pt,{ys[3]:.1f}pt) -- ({RX:.1f}pt,{ys[0]:.1f}pt) -- (s0.west);")
o(f"  \\node[lbl] at ({RX:.1f}pt,{ys[0]+14:.1f}pt) {{$\\circlearrowleft$}};")
o(f"  \\node[lbl, rotate=90] at ({RX-8:.1f}pt,{(ys[0]+ys[3])/2:.1f}pt) {{the loop closes here}};")

# what may close the loop
ptop, pbot = ys[0] + 14, ys[3] - 2
o(f"  \\draw[panel] ({PX:.1f}pt,{ptop:.1f}pt) rectangle ({PX+PW:.1f}pt,{pbot:.1f}pt);")
o(f"  \\node[head] at ({PX+11:.1f}pt,{ptop-11:.1f}pt) {{what may close the loop}};")
o(f"  \\draw[draw=lprule, line width=0.5pt] ({PX+11:.1f}pt,{ptop-18:.1f}pt) -- ({PX+PW-11:.1f}pt,{ptop-18:.1f}pt);")
for i, (rung, name) in enumerate(MODES):
    y = ptop - 30 - i * 17.5
    o(f"  \\node[rung] at ({PX+16:.1f}pt,{y:.1f}pt) {{{rung}}};")
    o(f"  \\node[mode] at ({PX+38:.1f}pt,{y:.1f}pt) {{{name}}};")
ax = PX + PW - 9
o(f"  \\draw[axis] ({ax:.1f}pt,{pbot+12:.1f}pt) -- ({ax:.1f}pt,{ptop-26:.1f}pt);")
o(f"  \\node[font=\\fontsize{{5.9}}{{6.5}}\\selectfont, text=lpgrey, rotate=90] "
  f"at ({ax-7:.1f}pt,{(ptop+pbot)/2-6:.1f}pt) {{increasing strength of evidence}};")
o(f"  \\draw[hint] (s1.east) -- ({PX-2:.1f}pt,{ys[1]:.1f}pt);")

o(r"\end{tikzpicture}")
o(r"\endgroup")
o(r"\caption{The discovery loop, and what may close it. A represented hypothesis is put to an "
  r"experiment or evaluation, which yields evidence, which is acted on by retaining, revising or "
  r"rejecting the hypothesis. The six things that can play the role of experiment or evaluation "
  r"are listed beside that stage, in increasing order of the strength of evidence they produce. "
  r"A hypothesis that is not represented cannot be revised on evidence, so the return edge is the "
  r"part of the cycle that a system's representation determines.}")
o(r"\label{fig:loop}")
o(r"\end{figure*}")

os.makedirs("review", exist_ok=True)
open("review/fig-loop.tex", "w").write("\n".join(L) + "\n")
print("wrote review/fig-loop.tex")
